[tool.black]
line-length = 88  # The black default is a good compromise.
skip-string-normalization = 1
target-version = ['py34']
include = '\.py$'
extend-exclude = '''
/(
  \.toml
  |\.sh
  |\.git
  |\.md
  |\.txt
  |\.yml
  |\.ui
  |\.mel
)/
'''

[tool.ruff]
# Same as Black.
line-length = 88

# Assume Python 3.7
target-version = "py37"

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
